Add a Windows application manifest (#1193)
Add a Windows application manifest using
[embed-resource](https://crates.io/crates/embed-resource).

This enable long path support on windows without manifest av1an failed
with the following error.
```
Error: Failed to get number of frames for input video

Caused by:
    0: get_clip_info
    1: An error occurred in VSScript
    2: Python exception: Source path does not exist

       Traceback (most recent call last):
         File "src/cython/vapoursynth.pyx", line 3393, in vapoursynth._vpy_evaluate
         File "src/cython/vapoursynth.pyx", line 3394, in vapoursynth._vpy_evaluate
         File "<string>", line 26, in <module>
       ValueError: Source path does not exist
```